# syntax = docker/dockerfile:1.3-labs
ARG BASE_IMAGE=nvcr.io/nvidia/pytorch:24.03-py3

FROM $BASE_IMAGE AS base

RUN pip3 install --upgrade transformers

# colmap
RUN apt-get update -y
RUN apt-get install python3 python3-pip unzip wget -y
#install ceres-solver and colmap
RUN apt-get install \
    git \
    cmake \
    build-essential \
    libboost-program-options-dev \
    libboost-filesystem-dev \
    libboost-graph-dev \
    libboost-regex-dev \
    libboost-system-dev \
    libboost-test-dev \
    libeigen3-dev \
    libsuitesparse-dev \
    libfreeimage-dev \
    libgoogle-glog-dev \
    libgflags-dev \
    libglew-dev \
    qtbase5-dev \
    libqt5opengl5-dev \
    libcgal-dev -y

RUN apt-get install libcgal-qt5-dev -y
RUN apt-get install libatlas-base-dev libsuitesparse-dev -y
RUN git clone https://ceres-solver.googlesource.com/ceres-solver /ceres-solver
WORKDIR /ceres-solver
RUN git checkout $(git rev-parse --short HEAD)
RUN mkdir build
WORKDIR /ceres-solver/build
RUN cmake .. -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF
RUN make -j4
RUN make install
WORKDIR /

# RUN apt-get install libflann-dev -y

RUN apt-get install -y liblz4-dev
RUN git clone git://github.com/mariusmuja/flann.git /flann
WORKDIR /flann
RUN mkdir build
WORKDIR /flann/build
RUN cmake .. -DCMAKE_CUDA_ARCHITECTURES=native
RUN make -j4
RUN make install



RUN apt-get install libsqlite3-dev -y
RUN apt-get install libmetis-dev -y

RUN git clone https://github.com/colmap/colmap.git /colmap
WORKDIR /colmap
# 3.9.1 + patch
RUN git checkout 3.9.1
RUN git config --global user.email "you@example.com" && git config --global user.name "Your Name"
RUN git cherry-pick 71cebde85b5ce290c93f67326eea7c1b1c0cea97
RUN mkdir build
WORKDIR /colmap/build
# RUN sed -i '/#include "thirdparty\/LSD\/lsd.h"/a #include <memory>' /colmap/src/colmap/image/line.cc
RUN cmake .. -DCMAKE_CUDA_ARCHITECTURES=native
RUN make -j
RUN make install
WORKDIR /


RUN pip3 install git+https://github.com/mihaidusmanu/pycolmap
RUN pip3 install --upgrade \
    scikit-learn \
    ipywidgets \
    polars \
    catboost \
    lightgbm \
    transformers \
    datasets \
    sentence-transformers \
    gradio \
    seaborn \
    polyleven \
    optuna \
    pytorch_lightning \
    mlxtend \
    fastprogress \
    h5py \
    opencv-contrib-python \
    kornia \
    pillow \
    timm

